### ISSUE TITLE
Error in IE 8 

### ISSUE THREAD

**Issue by macsupport** [cmpolis/Pagify#6]
I'm a Mac user but need to make sure my pages work in IE ( at least 8 and 9) and find this error on my sites as well as your demo:

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; SearchToolbar 1.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
Timestamp: Thu, 29 Sep 2011 16:45:33 UTC

Message: Expected identifier, string or number
Line: 16
Char: 7
Code: 0
URI: http://cmpolis.github.com/Pagify/pagify.js

Message: Expected identifier, string or number
Line: 16
Char: 11
Code: 0
URI: http://cmpolis.github.com/Pagify/

Mike

**Comment by hermanschutte** [comment]
This is because of the default keyword being used to set an option. I've submitted a pull request that would fix this (https://github.com/cmpolis/Pagify/pull/10). In the meantime, you can test if it resolves your issue by accessing the gh-pages on my fork of this project: http://hermanschutte.github.com/Pagify/

**Comment by cmpolis** [comment]
Thanks for the report @macsupport and the code @hermanschutte! I pulled in the fix.

**Comment by niceoutput** [comment]
Your plugin doesn't work in ie7 and ie8.... :(
