### ISSUE TITLE
Demo not working in Android Gingerbread 

### ISSUE THREAD

**Issue by standardspace** [cmpolis/Pagify#9]
Can see nav but no content

**Comment by hermanschutte** [comment]
This is because of the default keyword being used to set an option. I've submitted a pull request that would fix this (https://github.com/cmpolis/Pagify/pull/10). In the meantime, you can test if it resolves your issue by accessing the gh-pages on my fork of this project: http://hermanschutte.github.com/Pagify/

**Comment by standardspace** [comment]
Hi Herman,
Yes your fork works fine
